name: BloodyMary

options:
  minimumXcodeGenVersion: "2.11.0"
  bundleIdPrefix: com.theInkedEngineer
  indentWidth: 2
  xcodeVersion: 11.3
  deploymentTarget:
    iOS: "10.0"
  generateEmptyDirectories: true
  
targets:
  BloodyMary:
    type: framework
    platform: iOS
    attributes:
      ProvisioningStyle: Automatic
    sources: [BloodyMary]
    info:
      path: BloodyMary/Resources/Info.plist
      properties:
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundlePackageType: "FMWK"
    settings:
      TARGETED_DEVICE_FAMILY: 1,2
      SUPPORTS_MACCATALYST: "NO"
  
  BloodyMaryDemo:
    type: application
    platform: iOS
    attributes:
      ProvisioningStyle: Automatic
    sources: [BloodyMaryDemo]
    info:
      path: BloodyMaryDemo/Resources/Info.plist
      properties:
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundlePackageType: "APPL"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: "LaunchScreen"
        UIRequiredDeviceCapabilities: ["armv7"]
        UISupportedInterfaceOrientations: ["UIInterfaceOrientationPortrait"]
    settings:
      TARGETED_DEVICE_FAMILY: 1
    
schemes:
  Developement:
      build:
        targets:
          BloodyMary: all
      archive:
        customArchiveName: BloodyMary_Development
        revealArchiveInOrganizer: false
